#%RAML 1.0 NamedExample

value:
    -
        vehicle_id: 5eb5a6a3e311fc72b4c9f2d1
        brand: Ford
        model: fiesta
        year: 2020
        plate: NGV733
        additionalInfo: Vehiculo utilizado por el gerente
    

