#%RAML 1.0 NamedExample

value:
    -
        trip_id: 60c7c4e8a0d2a61e147d3b62
        vehicle:
            vehicle_id: 5eb5a6a3e311fc72b4c9f2d1
            plate: NGV733
        startDate: 2024-05-08T10:30:45Z
        endDate: 2024-05-09T11:30:00Z
        distance: 1250000
        duration: 90015
        user:
            user_id: 507f191e810c19729de860ea
            name: David Julian Castaño Ramirez
            email: davidj3311@hotmail.com
        movementTime: 70028
        staticTime: 19987
        averageSpeed: 138889
        maxSpeed: 140005
        averageTemperature: 32
        maxTemperature: 39
        startCordinates:
            latitude: 4.60971
            longitude: -74.08175
        endCordinates: 
            latitude: 15.83331
            longitude: -74.08175
