#%RAML 1.0 NamedExample

value:
    - 
        stadistics_id: 507f191e810c19729de860ea
        type: Velocidad máxima
        data: 85
        inference: En esta carretera la velocidad máxima son 80 km
        created_by: djcastanor
        created_at: 2024-05-08T12:30:45Z
        updated_by: djcastanor
        updated_at: 2024-05-08T12:30:45Z
        
